### ISSUE TITLE
MyPet causes server crash on 1.16.3

### ISSUE THREAD

**Issue by MrPowerGamerBR** [MyPetORG/MyPet#1409]
# Bug report

* [X] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

The server crashes randomly while MyPet is active

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

Judging by the stacktrace, looks like 1.16.3 changed some NMS methods to be unobfuscated, causing issues.

[ticket.zip](https://github.com/xXKeyleXx/MyPet/files/5209928/ticket.zip)

**Error:**
```
java.lang.NoSuchMethodError: 'int net.minecraft.server.v1_16_R2.EnumItemSlot.c()'
        at de.Keyle.MyPet.compat.v1_16_R2.entity.types.EntityMyFox.getEquipment(EntityMyFox.java:195)
        at net.minecraft.server.v1_16_R2.EntityTrackerEntry.a(EntityTrackerEntry.java:322)
        at net.minecraft.server.v1_16_R2.EntityTrackerEntry.b(EntityTrackerEntry.java:269)
        at net.minecraft.server.v1_16_R2.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:2432)
        at net.minecraft.server.v1_16_R2.PlayerChunkMap$EntityTracker.updatePlayers(PlayerChunkMap.java:2329)
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2042)
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.g(PlayerChunkMap.java:2063)
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:865)
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:743)
        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456)
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358)
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375)
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by ScuroK** [comment]
Same here.

**Comment by NoHoPeLess** [comment]
same

**Comment by niqoar** [comment]
Fix on commit #5d8b769?

**Comment by notbike** [comment]
same here

**Comment by ScuroK** [comment]
On the mypet discord they say it was fixed in the latest dev build (mypet-plugin.de)

I did not try it yet.

Man do i miss the time where all plugin informations were on one page (bukkit and later spigot) 😂

**Comment by notbike** [comment]
@ScuroK  I don't think it's fixed yet, I was using build 1571, had to revert back to build 1567

**Comment by yossy1zip** [comment]
same
@notbike could you give me 1567 one?

**Comment by MrPowerGamerBR** [comment]
It was fixed in the latest version, but now pet beacon is causing a lot of issues:
```
[16:00:27 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Tuinity-"1e695f4" (MC: 1.16.3) ---
[16:00:27 ERROR]: The server has not responded for 80 seconds! Creating thread dump
[16:00:27 ERROR]: ------------------------------
[16:00:27 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[16:00:27 ERROR]: ------------------------------
[16:00:27 ERROR]: Current Thread: Server thread
[16:00:27 ERROR]:       PID: 27 | Suspended: false | Native: false | State: RUNNABLE
[16:00:27 ERROR]:       Stack:
[16:00:27 ERROR]:               java.base@14.0.2/java.util.HashMap.putVal(HashMap.java:665)
[16:00:27 ERROR]:               java.base@14.0.2/java.util.HashMap.put(HashMap.java:613)
[16:00:27 ERROR]:               app//com.google.common.collect.AbstractMapBasedMultimap.put(AbstractMapBasedMultimap.java:197)
[16:00:27 ERROR]:               app//com.google.common.collect.AbstractSetMultimap.put(AbstractSetMultimap.java:130)
[16:00:27 ERROR]:               app//com.google.common.collect.LinkedHashMultimap.put(LinkedHashMultimap.java:86)
[16:00:27 ERROR]:               app//com.google.common.collect.ForwardingMultimap.put(ForwardingMultimap.java:98)
[16:00:27 ERROR]:               app//com.destroystokyo.paper.profile.CraftPlayerProfile.copyProfileProperties(CraftPlayerProfile.java:211)
[16:00:27 ERROR]:               app//com.destroystokyo.paper.profile.CraftPlayerProfile.copyProfileProperties(CraftPlayerProfile.java:198)
[16:00:27 ERROR]:               app//com.destroystokyo.paper.profile.CraftPlayerProfile.completeFromCache(CraftPlayerProfile.java:170)
[16:00:27 ERROR]:               app//org.bukkit.craftbukkit.v1_16_R2.inventory.CraftMetaSkull.setProfile(CraftMetaSkull.java:80)
[16:00:27 ERROR]:               app//org.bukkit.craftbukkit.v1_16_R2.inventory.CraftMetaSkull.setOwner(CraftMetaSkull.java:188)
[16:00:27 ERROR]:               de.Keyle.MyPet.skill.skills.BeaconImpl.<init>(BeaconImpl.java:83)
[16:00:27 ERROR]:               jdk.internal.reflect.GeneratedConstructorAccessor360.newInstance(Unknown Source)
[16:00:27 ERROR]:               java.base@14.0.2/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:00:27 ERROR]:               java.base@14.0.2/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[16:00:27 ERROR]:               java.base@14.0.2/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[16:00:27 ERROR]:               de.Keyle.MyPet.api.skill.SkillManager.getNewSkillInstance(SkillManager.java:123)
[16:00:27 ERROR]:               de.Keyle.MyPet.api.skill.Skills.<init>(Skills.java:42)
[16:00:27 ERROR]:               de.Keyle.MyPet.entity.MyPet.<init>(MyPet.java:134)
[16:00:27 ERROR]:               de.Keyle.MyPet.entity.types.MyCreeper.<init>(MyCreeper.java:34)
[16:00:27 ERROR]:               java.base@14.0.2/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:00:27 ERROR]:               java.base@14.0.2/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorA
```

**Comment by UserDerezzed** [comment]
MyPet no longer supports 1.16.3, please update to 1.16.5 and reopen this issue if the problem persists.
